export const mockProducts = [
  {
    name: 'Mitti Attar',
    nameHindi: 'मिट्टी अत्तर',
    subtitle: 'The Scent of First Rain on Earth',
    description: 'Capturing the quintessential Indian monsoon experience — the aroma of rain hitting sun-baked earth. This legendary attar is distilled using an ancient technique where baked earth is placed in the still alongside flowers, creating an unmistakable petrichor that no synthetic fragrance can replicate. One drop and you are standing in a traditional courtyard as the first clouds break.',
    price: 0.1,
    category: 'floral',
    tags: ['bestseller', 'monsoon', 'earthy', 'petrichor', 'unique'],
    notes: { top: ['Wet Earth', 'Ozone'], heart: ['Lotus', 'Jasmine'], base: ['Sandalwood', 'Amber'] },
    ingredients: ['Baked Earth', 'Lotus Petals', 'Jasmine', 'Sandalwood Oil'],
    volume: '12ml',
    image: '/images/mitti_attar.jpg',
    badge: 'Bestseller',
    colorSwatch: '#8B6914',
    featured: true,
    rating: 4.9,
    reviewCount: 287,
    origin: 'Uttar Pradesh, India'
  },
  {
    name: 'Gulab Attar',
    nameHindi: 'गुलाब अत्तर',
    subtitle: 'Premium Damask Rose — The Original',
    description: 'Our Gulab Attar uses only the finest Damask roses harvested at dawn from fields along the Ganges, when the essential oil content is at its absolute peak. Each 12ml bottle requires approximately 5,000 roses. The result is a honeyed, velvety rose that unfolds on skin for 12+ hours — nothing like the sharp rose oils of commercial perfumery.',
    price: 0.1,
    category: 'floral',
    tags: ['classic', 'rose', 'romantic', 'vday'],
    notes: { top: ['Fresh Rose Petals', 'Green Stem'], heart: ['Damask Rose', 'Honey'], base: ['Sandalwood', 'Musk'] },
    ingredients: ['Damask Rose', 'Sandalwood Oil Base'],
    volume: '12ml',
    image: 'https://images.unsplash.com/photo-1588405748880-12d1d2a59f75?w=800&h=1000&fit=crop',
    badge: 'Classic',
    colorSwatch: '#9B2335',
    featured: true,
    rating: 4.8,
    reviewCount: 412,
    origin: 'Uttar Pradesh, India'
  },
  {
    name: 'Chandan Attar',
    nameHindi: 'चंदन अत्तर',
    subtitle: 'Mysore Sandalwood — Sacred & Meditative',
    description: 'Sourced from government-regulated sandalwood plantations in Mysore, this is the real thing — creamy, buttery, meditative. True Mysore sandalwood oil has been prized for millennia, mentioned in the Vedas and used in every temple across India. Our Chandan Attar preserves this sacred essence in its purest form. The aroma deepens and warms over hours, making it perfect for meditation, prayer, or simply anchoring your day.',
    price: 0.1,
    category: 'woody',
    tags: ['sacred', 'meditation', 'temple', 'unisex'],
    notes: { top: ['Creamy Wood', 'Butter'], heart: ['Sandalwood', 'Balsam'], base: ['Musk', 'Ambergris'] },
    ingredients: ['Mysore Sandalwood', 'Base Oil'],
    volume: '12ml',
    image: '/images/chandan_attar.jpg',
    badge: '',
    colorSwatch: '#C4A35A',
    featured: true,
    rating: 4.9,
    reviewCount: 198,
    origin: 'Mysore, Karnataka'
  },
  {
    name: 'Oudh Attar',
    nameHindi: 'उद अत्तर',
    subtitle: 'Assamese Agarwood — Liquid Gold',
    description: 'Wild-harvested agarwood from the ancient forests of Assam, where the Aquilaria tree has been infected naturally to produce the rarest aromatic resin on Earth. Our Oudh Attar is dark, complex, and deeply evolving — opening with smoky leather, moving through camphoraceous green, and settling into an incredibly warm, animalic sweetness that lingers for 24+ hours. This is not the synthetic oud found in Western luxury brands.',
    price: 0.1,
    category: 'woody',
    tags: ['premium', 'oud', 'luxury', 'mens'],
    notes: { top: ['Smoke', 'Leather', 'Camphor'], heart: ['Agarwood', 'Incense'], base: ['Amber', 'Musk', 'Animalic'] },
    ingredients: ['Wild Assamese Agarwood', 'Sandalwood Oil Base'],
    volume: '12ml',
    image: 'https://images.unsplash.com/photo-1541643600914-78b084683601?w=800&h=1000&fit=crop',
    badge: 'Premium',
    colorSwatch: '#5C4033',
    featured: true,
    rating: 4.7,
    reviewCount: 134,
    origin: 'Assam'
  },
  {
    name: 'Bela Attar',
    nameHindi: 'बेला अत्तर',
    subtitle: 'Night-Blooming Jasmine — Intoxicating',
    description: 'In the quiet hours after midnight, the Jasmine sambac flowers release their most potent fragrance. Our pickers work in darkness to harvest these blossoms at their peak, and they go straight into the still before dawn. Bela Attar captures this nocturnal magic — an intoxicating, slightly indolic white floral that is deeply feminine yet powerful. In Indian tradition, Bela is the fragrance of love and longing.',
    price: 0.1,
    category: 'floral',
    tags: ['jasmine', 'night', 'feminine', 'romantic'],
    notes: { top: ['Green Bud', 'Tea'], heart: ['Jasmine Sambac', 'Orange Blossom'], base: ['Sandalwood', 'Vanilla'] },
    ingredients: ['Night Jasmine', 'Sandalwood Oil Base'],
    volume: '12ml',
    image: 'https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?w=800&h=1000&fit=crop',
    badge: '',
    colorSwatch: '#E8E0D0',
    featured: false,
    rating: 4.8,
    reviewCount: 176,
    origin: 'Madurai, Tamil Nadu'
  },
  {
    name: 'Kesar Attar',
    nameHindi: 'केसर अत्तर',
    subtitle: 'Kashmiri Saffron — The Emperor\'s Choice',
    description: 'Made with Grade-1 Kashmiri Mongra saffron — the most expensive spice on Earth, hand-picked from the valleys of Pampore. Each gram contains over 300 hand-harvested stigmas. Our Kesar Attar is extraordinarily rich, warm, and honey-sweet with a distinct leathery undertone that only the finest saffron possesses. This was the fragrance of Mughal courts, and it remains unmatched in the world of natural perfumery.',
    price: 0.1,
    originalPrice: 0.1,
    category: 'rare',
    tags: ['rare', 'saffron', 'royal', 'luxury', 'kashmir'],
    notes: { top: ['Honey', 'Warm Spice'], heart: ['Kashmiri Saffron', 'Rose'], base: ['Leather', 'Amber', 'Sandalwood'] },
    ingredients: ['Kashmiri Mongra Saffron', 'Damask Rose', 'Sandalwood Oil'],
    volume: '12ml',
    image: 'https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?w=800&h=1000&fit=crop',
    badge: 'Rare',
    colorSwatch: '#CC5500',
    featured: true,
    rating: 5.0,
    reviewCount: 89,
    origin: 'Pampore, Kashmir'
  },
  {
    name: 'Shamama Attar',
    nameHindi: 'शमामा अत्तर',
    subtitle: 'The Complex Masterpiece — 60+ Ingredients',
    description: 'Shamama is the most complex attar in Indian perfumery — a symphony of over 60 natural ingredients including saffron, agarwood, sandalwood, musk, amber, rose, jasmine, and dozens of rare herbs and spices. Each master distiller has their own recipe, passed down through generations. Our family recipe takes three full months to complete. This is not a fragrance — it is an experience.',
    price: 0.1,
    category: 'rare',
    tags: ['rare', 'complex', 'masterpiece', 'heirloom'],
    notes: { top: ['Saffron', 'Cardamom', 'Green Herbs'], heart: ['Rose', 'Jasmine', 'Oud', 'Sandalwood'], base: ['Amber', 'Musk', 'Leather', 'Incense'] },
    ingredients: ['60+ Natural Ingredients Including Saffron, Oud, Sandalwood, Rose, Amber, Musk'],
    volume: '12ml',
    image: '/images/shamama_attar.jpg',
    badge: 'Limited',
    featured: true,
    rating: 5.0,
    reviewCount: 47,
    origin: 'Uttar Pradesh, India'
  },
  {
    name: 'Hina Attar',
    nameHindi: 'हिना अत्तर',
    subtitle: 'Mehndi Flowers — Warm & Spiced Floral',
    description: 'Distilled from the tiny flowers of the henna (mehndi) plant, Hina Attar is one of the most unique fragrances in the world. The scent is warm, slightly spicy, and deeply floral with a characteristic hay-like sweetness. In Indian Muslim tradition, Hina is associated with celebration and joy — worn at weddings, Eid, and festive occasions. It layers beautifully with Oudh or Sandalwood.',
    price: 0.1,
    category: 'spicy',
    tags: ['spicy', 'floral', 'wedding', 'festive'],
    notes: { top: ['Hay', 'Green Spice'], heart: ['Henna Flower', 'Saffron'], base: ['Sandalwood', 'Amber', 'Musk'] },
    ingredients: ['Henna Flowers', 'Saffron', 'Sandalwood Oil'],
    volume: '12ml',
    image: 'https://images.unsplash.com/photo-1587017539504-67cfbddac569?w=800&h=1000&fit=crop',
    badge: '',
    colorSwatch: '#6B8E23',
    featured: false,
    rating: 4.6,
    reviewCount: 93,
    origin: 'Uttar Pradesh, India'
  },
  {
    name: 'Kewra Attar',
    nameHindi: 'केवड़ा अत्तर',
    subtitle: 'Pandanus Flowers — The Culinary Treasure',
    description: 'Kewra is distilled from the male flowers of the Pandanus (screw pine) tree that grows along India\'s coastlines. It is one of the most important flavouring agents in Indian cuisine — used in biryanis, sweets, and sharbats across the country. As a wearable fragrance, Kewra is ethereal, sweet-floral with a unique watery-green quality unlike any other flower. Refreshing in summer, comforting in winter.',
    price: 0.1,
    category: 'fresh',
    tags: ['fresh', 'culinary', 'summer', 'light'],
    notes: { top: ['Watery Green', 'Coconut'], heart: ['Pandanus Flower', 'Rose Water'], base: ['Sandalwood', 'Light Musk'] },
    ingredients: ['Pandanus Flowers', 'Sandalwood Oil'],
    volume: '12ml',
    image: 'https://images.unsplash.com/photo-1563170351-be82bc888aa4?w=800&h=1000&fit=crop',
    badge: 'New',
    colorSwatch: '#90EE90',
    featured: false,
    rating: 4.5,
    reviewCount: 61,
    origin: 'Ganjam, Odisha'
  }
];

export const mockTestimonials = [
  {
    name: 'Rukmani Pall',
    location: 'Mumbai, Maharashtra',
    initials: 'RP',
    text: 'The Mitti Attar transported me back to my grandmother\'s courtyard in Lucknow during the first monsoon rain. I wept. It was that real. No French perfume has ever moved me like this.',
    rating: 5,
    productName: 'Mitti Attar'
  },
  {
    name: 'Arjun Khanna',
    location: 'London, UK',
    initials: 'AK',
    text: 'I have worn Creed, Tom Ford, and Amouage for years. One drop of the Kesar Attar changed everything. The depth, the evolution on skin, the longevity — nothing in the West compares to this.',
    rating: 5,
    productName: 'Kesar Attar'
  },
  {
    name: 'Swami Shivanand',
    location: 'Rishikesh, Uttarakhand',
    initials: 'SS',
    text: 'We use the Chandan Attar in our ashram every morning for puja. The entire temple fills with such a sacred fragrance that devotees often ask what special incense we are burning. Pure prasad for the senses.',
    rating: 5,
    productName: 'Chandan Attar'
  },
  {
    name: 'Priya Mehta',
    location: 'New Delhi',
    initials: 'PM',
    text: 'I gifted the Shamama to my father for his 70th birthday. He recognized it immediately — his grandfather used to wear the same attar from the same family. Three generations connected by one scent.',
    rating: 5,
    productName: 'Shamama Attar'
  },
  {
    name: 'David Chen',
    location: 'Singapore',
    initials: 'DC',
    text: 'As a niche fragrance collector with over 200 bottles, I can say this Oudh Attar is genuinely exceptional. Wild Assam oud at this quality level is virtually impossible to find in commercial perfumery.',
    rating: 5,
    productName: 'Oudh Attar'
  },
  {
    name: 'Aisha Bano',
    location: 'Hyderabad',
    initials: 'AB',
    text: 'The Bela Attar is exactly how my mother\'s garden smelled at 2 AM — intoxicating, alive, almost surreal. I apply it on my wrists and the scent just blooms for the entire day. Sublime.',
    rating: 5,
    productName: 'Bela Attar'
  }
];
